- .gitignore
- build.gradle
- src/main/resources/application.properties
- src/main/resources/application.yml
- src/main/resources/prod/application-datasource.yml
- src/main/resources/prod/application-logging.yml
- src/main/resources/prod/application-prod.yml
- 의존성 추가 및 설정 파일 추가
- closed #4 
- JWT 사용을 위한 의존성 `build.gradle`에 추가
- `application.yml` 설정 파일 추가 및 prod와 연결시켜 놓고, prod 기준으로 설정 적용 함
- `.gitignore`에 local에서 사용하기 위한 설정 폴더인 local ignore 처리 함
`application.yml`이 현재 prod 폴더 내의 `application-prod.yml`로 연결되어 있습니다. 로컬에서 사용 시 `application-local.yml`로 연결해서 사용해주세요.
> Chore: 의존성 추가 및 설정 파일 추가

- src/main/java/com/outsourcing/domain/store/entitiy/Store.java
- src/main/java/com/outsourcing/domain/store/enums/StoreStatus.java
- 스토어 엔티티를 구현하고 관련 이넘을 구현했습니다.
- closed #11 
- PR 및 Issue 템플릿 추가
> feat : 스토어 엔티티 및 관련 이넘 생성

- src/main/java/com/outsourcing/common/exception/BaseException.java
- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/common/exception/ErrorCodeDto.java
- src/main/java/com/outsourcing/common/exception/GlobalControllerAdvice.java
- src/main/java/com/outsourcing/common/exception/ValidationErrorDto.java
- src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
- src/main/java/com/outsourcing/common/filter/JwtAuthorizationFilter.java
- src/main/java/com/outsourcing/common/response/ErrorResponse.java
- src/main/java/com/outsourcing/common/response/Response.java
- src/main/java/com/outsourcing/common/response/SuccessResponse.java
- src/main/java/com/outsourcing/domain/auth/service/AuthService.java
- 응답 구조 변경
- closed #14 
- 응답 구조의 확장성을 위해 data와 동일하게 depth 0에 error를 두고 depth 1에 실제 전달 받은 데이터를 출력하도록 설정
- 구조 변경으로 인한 코드 일부 변경
| 기능 | 스크린샷 |
| --- | --- |
| 구조 변경 이전 | ![image](https://github.com/user-attachments/assets/fb8391a0-086e-4731-aa1c-15d63f7d857b) |
| 구조 변경 이후 (1) | ![스크린샷 2025-03-03 000416](https://github.com/user-attachments/assets/ad0c9f3d-10c9-487a-9a18-26129e8d31ec) |
| 구조 변경 이후 (2) | ![스크린샷 2025-03-02 234342](https://github.com/user-attachments/assets/cb763368-ca86-42d2-ab58-fec0ccf955e2) |
> Chore: 응답 구조 변경

- src/main/java/com/outsourcing/domain/auth/controller/AuthOwnerController.java
- src/main/java/com/outsourcing/domain/auth/service/AuthCommonService.java
- src/main/java/com/outsourcing/domain/auth/service/AuthCustomerService.java
- src/main/java/com/outsourcing/domain/auth/service/AuthOwnerService.java
- src/main/java/com/outsourcing/domain/user/service/CustomerService.java
- src/main/java/com/outsourcing/domain/user/service/OwnerService.java
- `Auth` 리팩토링
- closed #22 
- `RefreshTokenRepositoryImpl`를 의존하고 있던 코드를 `RefreshTokenRepository`를 의존하도록 변경 (`=인터페이스 의존하도록 변경`)
- 메서드 네이밍 컨벤션이 맞지 않던 부분 수정 (pascal -> camel)
- 너무 긴 변수명은 간결하게 변경함
> Refactor: `Auth` 리팩토링

- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/domain/user/service/CustomerService.java
- 주소 변경 및 삭제 수정
- closed #30
- 권한 확인이 없어 사용자 A의 주소를 사용자 B가 수정할 수 있던 버그 수정
| 기능 | 스크린샷 |
| --- | --- |
| 코드 수정 전 요청 | ![스크린샷 2025-03-04 112750](https://github.com/user-attachments/assets/9fbd5e53-d70a-418a-9223-27ae7561d227) |
| 코드 수정 전 요청 결과 | ![스크린샷 2025-03-04 112739](https://github.com/user-attachments/assets/ef71ff95-6784-4952-b1af-f48ca575b689) |
| 코드 수정 전 데이터베이스 | ![스크린샷 2025-03-04 112801](https://github.com/user-attachments/assets/936672e1-b32c-4f46-93b3-2d00e074d833) |
| 코드 수정 후 요청 | ![스크린샷 2025-03-04 112921](https://github.com/user-attachments/assets/4856ef6d-7754-4ba0-b797-14e371a3c7f8) |
| 코드 수정 후 요쳥 결과 | ![스크린샷 2025-03-04 112857](https://github.com/user-attachments/assets/10a85a0b-4f34-49a5-a353-77e5ad27bb1a) |
| 코드 수정 후 데이터베이스 | ![스크린샷 2025-03-04 …
> Fix: 주소 변경 및 삭제 수정

- src/main/java/com/outsourcing/common/response/Response.java
- src/main/java/com/outsourcing/common/response/SuccessResponse.java
- src/main/java/com/outsourcing/domain/auth/controller/AuthCommonController.java
- src/main/java/com/outsourcing/domain/auth/controller/AuthCustomerController.java
- src/main/java/com/outsourcing/domain/auth/controller/AuthOwnerController.java
- src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
- src/main/java/com/outsourcing/domain/user/controller/OwnerController.java
- 성공 응답 시 메시지 제거
- closed #35
- `SuccessResponse`에서 message 제거
- `Response`에서 message 제거
> Chore: 성공 응답 시 메시지 제거

- build.gradle
- src/main/java/com/outsourcing/common/util/s3/S3Config.java
- src/main/java/com/outsourcing/domain/menu/controller/MenuController.java
- src/main/java/com/outsourcing/domain/order/entity/Order.java
- src/main/java/com/outsourcing/domain/order/entity/OrderItem.java
- aws 의존성 추가 및 S3 설정
- closed #33
- spring cloud aws starter 의존성 추가
- aws java sdk 의존성 추가
- S3 설정 클래스 `S3Config` 추가
- 코드 일부 수정 (`OrderService` return 값이 없어서 애플리케이션 실행은 안됨)
- `Order` 클래스 `@Table(name = "orders")`로 변경
- `OrderItem` 클래스에 `@Table(name = "order_items")` 추가 및 필요없는 컬럼 제거
> Chore: aws 의존성 추가 및 S3 설정

- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/common/storage/StorageService.java
- src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
- src/main/java/com/outsourcing/common/storage/dto/response/UploadResponse.java
- src/main/java/com/outsourcing/common/storage/enums/UploadType.java
- src/main/java/com/outsourcing/common/storage/s3/S3StorageService.java
- src/main/java/com/outsourcing/common/util/FileUtils.java
- src/main/java/com/outsourcing/config/S3Config.java
- src/main/java/com/outsourcing/config/SecurityConfig.java
- S3 이미지 업로드 구현
- ref #29 
- 확장성을 위해 `StorageService` 인터페이스를 구현하도록 함
- `UploadType`으로 세부 폴더와 해당 폴더에 대한 접근 가능 여부를 판단함 (어떤 항목에 대한 이미지인지 & 그 항목에 접근이 가능한 역할인지)
- 고유한 파일명을 만들어주는 `FileUtils` 생성
- mulipartfile을 받기 위해 `@RequestPart` 사용 (좀 더 알아본 뒤에 제대로 적용할 것인지 판단할 예정)
- `SecurityConfig`에 `requestMatchers` 추가
| 기능 | 스크린샷 |
| --- | --- |
| Customer가 profiles로 요청 | ![스크린샷 2025-03-05 114333](https://github.com/user-attachments/assets/65f2cde3-5fd8-491d-bb35-deafb1bc7662) |
| Customer가 file이 아닌 text로 요청 | ![스크린샷 2025-03-05 114450](https://github.com/user-attachments/assets/6d81c9cb-c136-4a5f-bf04-768f7cfdc70d) |
| Customer가 file이 아닌 text로 요청 시 콘솔 창 | ![스크린샷 2025-03-05 114501](https://github.com/user-attachments/assets/1d70eade-44c9-4198-a23f-ce85ff03c648) |
| Customer가 pdf로 요청(이미지 …
> Feat: S3 이미지 업로드 구현

- build.gradle
- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
- src/main/java/com/outsourcing/common/storage/service/StorageService.java
- src/main/java/com/outsourcing/common/storage/service/s3/S3StorageService.java
- src/main/java/com/outsourcing/common/util/FileUtils.java
- 이미지 리사이징 구현
- closed #44 
- 리사이징 적용을 위한 thumbnailator 의존성 추가
- 파일 구조 일부 변경
- `FileUtils`에 이미지 리사이징을 수행하는 resize 메서드 추가 및 구현
- `S3StorageService`에서 putObject 시 리사이징된 이미지 & 이미지 크기를 넣어서 저장하도록 수정
> Feat: 이미지 리사이징 구현

- .gitignore
- src/main/java/com/outsourcing/config/PropertyConfig.java
- src/main/java/com/outsourcing/config/SecurityConfig.java
- properties 빈 등록을 위한 `PropertyConfig` 생성 후 적용
- closed #47 
- 새로운 API 추가 (예: `/users`)
- 기존 로직 리팩토링 (예: UserService)
- 테스트 코드 추가
> Chore: properties 빈 등록을 위한 `PropertyConfig` 생성 후 적용

- src/main/java/com/outsourcing/domain/auth/service/AuthCommonService.java
- src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
- src/main/java/com/outsourcing/domain/user/controller/OwnerController.java
- src/main/java/com/outsourcing/domain/user/dto/request/DeleteUserRequest.java
- src/main/java/com/outsourcing/domain/user/service/CustomerService.java
- src/main/java/com/outsourcing/domain/user/service/OwnerService.java
- `User` 관련 리팩토링
- closed #49 
- 로그아웃 메서드 조건문 변경
- 회원 탈퇴 시 request 헤더에서 값을 가져올 때 오타 방지를 위해 Const 클래스 사용
- 가독성을 위한 단순 수정
- 코드에 주석 달아 놓음
> Refactor: `User` 관련 리팩토링

- src/main/java/com/outsourcing/domain/user/dto/response/CustomerResponse.java
- src/main/java/com/outsourcing/domain/user/dto/response/OwnerResponse.java
- 객체의 id 값을 응답 필드에 추가
- `CustomerResponse` 필드와 return 할 때 id 값 추가
- `OwnerResponse` 필드와 return 할 때 id 값 추가
> Refactor: 객체의 id 값을 응답 필드에 추가

- src/main/java/com/outsourcing/common/constant/Const.java
- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
- src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
- src/main/java/com/outsourcing/common/util/jwt/JwtTokenProvider.java
- src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
- src/main/java/com/outsourcing/domain/user/entity/Owner.java
- 다중 파일 업로드 시 최대 3개까지 가능하도록 수정
- closed #57
- 그 외 오타 방지를 위한 `Const` 내용 추가 후 해당 상수를 사용하도록 수정
- 메서드명 수정
> Refactor: 다중 파일 업로드 시 최대 3개까지 가능하도록 수정

- src/main/java/com/outsourcing/config/SecurityConfig.java
- src/main/java/com/outsourcing/domain/auth/controller/AuthUserController.java
- src/main/java/com/outsourcing/domain/auth/service/AuthUserService.java
- `SecurityConfig` 설정 추가
- orders 공통 로직 API 엔드포인트 추가
- Common -> User로 클래스 이름 변경
> Refactor: `SecurityConfig` 설정 추가

- src/main/java/com/outsourcing/domain/user/repository/CustomerRepository.java
- src/main/java/com/outsourcing/domain/user/repository/OwnerRepository.java
- src/main/java/com/outsourcing/domain/user/service/CustomerService.java
- src/main/java/com/outsourcing/domain/user/service/OwnerService.java
- user 패키지 내 사용하지 않는 필드 및 메서드 제거
- CustomerReporsitory & OwnerRepository 에서 사용하지 않는 메서드 제거
- CustomerService & OwnerService 에서 사용하지 않는 필드 제거
- 사용하지 않는 import 구문 제거
> Refactor: user 패키지 내 사용하지 않는 필드 및 메서드 제거

- src/test/java/com/outsourcing/domain/user/service/OwnerServiceTest.java
- OwnerService 테스트 코드 작성
- ref #50 
| 기능 | 스크린샷 |
| --- | --- |
| PNG | ![스크린샷 2025-03-06 215138](https://github.com/user-attachments/assets/45da09c9-c3ca-477c-9682-64c3cb54f859) |
> Test: OwnerService 테스트 코드 작성

- src/main/java/com/outsourcing/domain/user/service/CustomerService.java
- src/test/java/com/outsourcing/domain/user/service/CustomerServiceTest.java
- `CustomerService` 테스트 코드 작성
- ref #50
`CustomerService` 테스트 코드 작성
> Test: `CustomerService` 테스트 코드 작성

- src/main/java/com/outsourcing/common/exception/ErrorCode.java
- src/main/java/com/outsourcing/config/SecurityConfig.java
- src/main/java/com/outsourcing/domain/order/controller/OwnerOrderController.java
- src/main/java/com/outsourcing/domain/order/controller/UserOrderController.java
- src/main/java/com/outsourcing/domain/order/repository/OrderRepository.java
- src/main/java/com/outsourcing/domain/order/service/OwnerOrderService.java
- src/main/java/com/outsourcing/domain/order/service/UserOrderService.java
- src/main/java/com/outsourcing/domain/review/controller/ReviewController.java
- src/main/java/com/outsourcing/domain/review/controller/ReviewReplyController.java
- src/main/java/com/outsourcing/domain/review/dto/request/ReviewReplyRequest.java
- src/main/java/com/outsourcing/domain/review/dto/request/ReviewReplyUpdateRequest.java
- src/main/java/com/outsourcing/domain/review/dto/request/ReviewRequest.java
- src/main/java/com/outsourcing/domain/review/dto/request/ReviewUpdateRequest.java
- src/main/java/com/outsourcing/domain/review/dto/response/ReviewReplyResponse.java
- src/main/java/com/outsourcing/domain/review/dto/response/ReviewResponse.java
- src/main/java/com/outsourcing/domain/review/entity/Image.java
- src/main/java/com/outsourcing/domain/review/entity/Review.java
- src/main/java/com/outsourcing/domain/review/entity/ReviewReply.java
- src/main/java/com/outsourcing/domain/review/repository/ImageRepository.java
- src/main/java/com/outsourcing/domain/review/repository/ReviewReplyRepository.java
- src/main/java/com/outsourcing/domain/review/repository/ReviewRepository.java
- src/main/java/com/outsourcing/domain/review/service/ReviewReplyService.java
- src/main/java/com/outsourcing/domain/review/service/ReviewService.java
- 리뷰 관련 오류 메시지 추가
- 사용자 리뷰 C,R,U,D 추가
- 관리자 리뷰 대댓 C,R,U,D 추가
- Order 코드 수정
- 리뷰 관련 기능 추가.
- closed #123
- 새로운 API 추가 (예: `/users`)
- 기존 로직 리팩토링 (예: UserService)
- 테스트 코드 추가
> feat : 리뷰 및 대댓리뷰 기능 추가.

- src/main/java/com/outsourcing/domain/order/controller/UserOrderController.java
- src/main/java/com/outsourcing/domain/order/service/UserOrderService.java
- 피드백 반영
- order 취소 기능 수정
- closed #123
- 새로운 API 추가 (예: `/users`)
- 기존 로직 리팩토링 (예: UserService)
- 테스트 코드 추가
> refactor : 주문 취소 기능 수정

- src/main/java/com/outsourcing/common/annotation/LogTrace.java
- src/main/java/com/outsourcing/common/aspect/LogTraceAspect.java
- src/main/java/com/outsourcing/domain/order/controller/CustomerOrderController.java
- src/main/java/com/outsourcing/domain/order/controller/OwnerOrderController.java
- src/main/java/com/outsourcing/domain/order/controller/UserOrderController.java
- 이 PR에서 어떤 작업이 이루어졌는지 간단히 설명해주세요.
- closed #74 
- AOP로 주문 생성, 조리 시작, 배달 시작, 배달 완료, 주문 취소에 대한 로깅 적용
| 기능 | 스크린샷 |
| --- | --- |
| 요청 로그 | ![스크린샷 2025-03-07 074500](https://github.com/user-attachments/assets/21839f23-0c66-44da-a8c3-b9d3bf74532a) |
| 응답 로그 | ![스크린샷 2025-03-07 074523](https://github.com/user-attachments/assets/2300ae57-4b78-45fc-a68c-a3d67fd52a50) |
> Feat: AOP 적용

- src/test/java/com/outsourcing/domain/user/service/CustomerServiceTest.java
- src/test/java/com/outsourcing/domain/user/service/UserServiceTest.java
- `UserService` 테스트 코드 작성
- ref #50 
> Test: `UserService` 테스트 코드 작성

- src/main/resources/application.yml
- src/main/resources/prod/application-datasource.yml
- src/main/resources/prod/application-prod.yml
- src/main/resources/prod/application-secret.yml
- `application.yml` 내용 추가 및 prod로 연결
- closed #77 
- `application.yml` prod와 연결
> Chore: `application.yml` 내용 추가 및 prod로 연결

- src/main/resources/schema.sql
- schemq.sql 작성
- schemq.sql 작성
> Chore: schemq.sql 작성

- src/test/java/com/outsourcing/domain/store/service/StoreCustomerServiceTest.java
- 이 PR에서 어떤 작업이 이루어졌는지 간단히 설명해주세요.
- closed #59 
- `StoreCustomerServiceTest` 테스트 코드 작성
| 기능 | 스크린샷 |
| --- | --- |
| 테스트 커버리지 | ![image](https://github.com/user-attachments/assets/66b8f53e-8cc9-418e-a7ce-c665b05b9601) |
> Test: `StoreCustomerServiceTest` 테스트 코드 작성
